<template>
  <div class="loadingio-spinner-eclipse-fumux3hqk19">
    <div class="ldio-bn6j0vmanrk">
      <div></div>
    </div>
  </div>
</template>
<style>
@keyframes ldio-bn6j0vmanrk {
  0% {
    transform: rotate(0deg);
  }

  50% {
    transform: rotate(180deg);
  }

  100% {
    transform: rotate(360deg);
  }
}

.ldio-bn6j0vmanrk div {
  position: absolute;
  animation: ldio-bn6j0vmanrk 1s linear infinite;
  width: 160px;
  height: 160px;
  top: 20px;
  left: 20px;
  border-radius: 50%;
  box-shadow: 0 4px 0 0 gray;
  transform-origin: 80px 82px;
}

.loadingio-spinner-eclipse-fumux3hqk19 {
  position: absolute;
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}

.ldio-bn6j0vmanrk {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;
  /* see note above */
}

.ldio-bn6j0vmanrk div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>