<template>
  <div class="loading-spinner-container">
    <div class="spinner-animation">
      <div></div>
    </div>
  </div>
</template>
<style>
@keyframes spinner-animation {
  0% {
    transform: rotate(0deg);
  }

  50% {
    transform: rotate(180deg);
  }

  100% {
    transform: rotate(360deg);
  }
}

.spinner-animation div {
  position: absolute;
  animation: spinner-animation 1s linear infinite;
  width: 160px;
  height: 160px;
  top: 20px;
  left: 20px;
  border-radius: 50%;
  box-shadow: 0 4px 0 0 #f14c39;
  transform-origin: 80px 82px;
}

.loading-spinner-container {
  position: absolute;
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}

.spinner-animation {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;
  /* see note above */
}

.spinner-animation div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>